In [1]:
import pandas as pd
import numpy as np

In [2]:
# Step 2 : Get/Load the Data

In [3]:
lcn=pd.read_csv(r"LungCapData.csv")

In [4]:
lcn.head()

LungCap  Age  Height Smoke  Gender Caesarean
0    6.475    6    62.1    no    male        no
1   10.125   18    74.7   yes  female        no
2    9.550   16    69.7    no  female       yes
3   11.125   14    71.0    no    male        no
4    4.800    5    56.9    no    male        no

In [5]:
# Step 3 : Data Cleaning and Preprocessing

In [6]:
lcn.shape

(725, 6)

In [7]:
lcn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 725 entries, 0 to 724
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   LungCap    725 non-null    float64
 1   Age        725 non-null    int64  
 2   Height     725 non-null    float64
 3   Smoke      725 non-null    object 
 4   Gender     725 non-null    object 
 5   Caesarean  725 non-null    object 
dtypes: float64(2), int64(1), object(3)
memory usage: 34.1+ KB


In [8]:
lcn.isnull().sum()

LungCap      0
Age          0
Height       0
Smoke        0
Gender       0
Caesarean    0
dtype: int64

In [9]:
lcn.Smoke = lcn.Smoke.replace({'no':0 , 'yes':1})

In [10]:
lcn.Gender.replace({'male':1 , 'female':0} , inplace=True)

In [11]:
lcn.Caesarean.replace({'no':0 , 'yes':1} , inplace=True)

In [12]:
lcn.head()

LungCap  Age  Height  Smoke  Gender  Caesarean
0    6.475    6    62.1      0       1          0
1   10.125   18    74.7      1       0          0
2    9.550   16    69.7      0       0          1
3   11.125   14    71.0      0       1          0
4    4.800    5    56.9      0       1          0

In [13]:
lcn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 725 entries, 0 to 724
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   LungCap    725 non-null    float64
 1   Age        725 non-null    int64  
 2   Height     725 non-null    float64
 3   Smoke      725 non-null    int64  
 4   Gender     725 non-null    int64  
 5   Caesarean  725 non-null    int64  
dtypes: float64(2), int64(4)
memory usage: 34.1 KB


In [14]:
# Step 4 : Sampling

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
lcn_train, lcn_test = train_test_split(lcn, test_size = 0.2)

In [17]:
lcn_train

LungCap  Age  Height  Smoke  Gender  Caesarean
242    6.575    8    59.8      0       0          0
339   10.250   18    72.5      0       0          0
579    8.225    7    65.7      0       1          0
2      9.550   16    69.7      0       0          1
246    8.000    9    66.4      0       1          0
..       ...  ...     ...    ...     ...        ...
87     7.750   11    63.5      0       0          0
658    6.500   14    61.7      1       0          0
52     7.400   11    65.3      0       1          0
238    9.475   17    64.8      1       0          0
707    5.275   12    58.5      0       0          1

[580 rows x 6 columns]

In [18]:
lcn_test

LungCap  Age  Height  Smoke  Gender  Caesarean
446    6.300   11    59.0      0       0          0
451    4.425    9    57.1      0       1          1
254    5.300    7    57.3      0       1          1
405    8.775   13    68.1      0       0          0
171    4.325    6    56.6      0       1          0
..       ...  ...     ...    ...     ...        ...
315    7.300   12    67.5      0       1          0
292    5.475    3    52.9      0       1          0
636    9.050   15    65.3      0       1          1
5      6.225   11    58.7      0       0          0
653    7.800   13    65.4      0       0          0

[145 rows x 6 columns]

In [19]:
lcn_train_x = lcn_train.iloc[:,1::]
lcn_test_x = lcn_test.iloc[:,1::]

In [20]:
lcn_train_x

Age  Height  Smoke  Gender  Caesarean
242    8    59.8      0       0          0
339   18    72.5      0       0          0
579    7    65.7      0       1          0
2     16    69.7      0       0          1
246    9    66.4      0       1          0
..   ...     ...    ...     ...        ...
87    11    63.5      0       0          0
658   14    61.7      1       0          0
52    11    65.3      0       1          0
238   17    64.8      1       0          0
707   12    58.5      0       0          1

[580 rows x 5 columns]

In [21]:
lcn_test_x

Age  Height  Smoke  Gender  Caesarean
446   11    59.0      0       0          0
451    9    57.1      0       1          1
254    7    57.3      0       1          1
405   13    68.1      0       0          0
171    6    56.6      0       1          0
..   ...     ...    ...     ...        ...
315   12    67.5      0       1          0
292    3    52.9      0       1          0
636   15    65.3      0       1          1
5     11    58.7      0       0          0
653   13    65.4      0       0          0

[145 rows x 5 columns]

In [22]:
lcn_train_y = lcn_train.iloc[:,0]
lcn_test_y = lcn_test.iloc[:,0]

In [23]:
lcn_train_y

242     6.575
339    10.250
579     8.225
2       9.550
246     8.000
        ...  
87      7.750
658     6.500
52      7.400
238     9.475
707     5.275
Name: LungCap, Length: 580, dtype: float64

In [24]:
lcn_test_y

446    6.300
451    4.425
254    5.300
405    8.775
171    4.325
       ...  
315    7.300
292    5.475
636    9.050
5      6.225
653    7.800
Name: LungCap, Length: 145, dtype: float64

In [25]:
# Model Building

In [26]:
# import the necessary function from sklearn
# create an object of that function 
# Run the fit function & model is created
# Run the prediction by using predict function

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
linereg = LinearRegression()

In [29]:
linereg.fit(lcn_train_x, lcn_train_y)

LinearRegression()

In [30]:
# Evaluating

In [31]:
Rsq = linereg.score(lcn_train_x, lcn_train_y)
Rsq

0.851024301402314

In [32]:
N = lcn_train_x.shape[0]
K = lcn_train_x.shape[1]

In [33]:
Adj_Rsq = 1 - (1-Rsq)*(N-1)/(N-K-1)
Adj_Rsq

0.8497266036793376

In [34]:
lcn_train.columns

Index(['LungCap', 'Age', 'Height', 'Smoke', 'Gender', 'Caesarean'], dtype='object')

In [35]:
linereg.coef_

array([ 0.15998598,  0.26086639, -0.60240589,  0.38347603, -0.27898674])

In [36]:
linereg.intercept_

-11.07481025414339

In [37]:
pred_train = linereg.predict(lcn_train_x)
pred_test = linereg.predict(lcn_test_x)

In [38]:
pred_train

array([ 5.80488755, 10.71775045,  7.56748928,  9.38836588,  8.07006771,
        5.01882224,  8.36048688, 10.6031482 , 11.99960463,  4.94402847,
        7.01888025,  7.8613746 ,  7.40324754,  6.62500578,  5.80835369,
        9.76144346,  6.9448761 ,  7.35004026,  8.51700671,  9.30213967,
        4.57188323,  6.67961121,  8.00670638,  7.6074405 , 13.52728388,
        8.16669235,  8.88915195, 10.86490585,  8.08845139, 10.33881566,
        6.62411452,  9.81363569,  8.35020904, 10.14143121,  5.83444033,
        3.40145064,  5.71187178,  9.04127328,  5.27968863,  7.98394315,
       10.18126183,  8.09615435,  5.85706082,  8.22129778, 10.08127269,
        7.01888025, 12.30467801,  7.94231104, 10.17868695,  6.88498091,
        9.69013479, 10.85604829,  7.39874739,  7.11961792,  8.92217088,
        8.09175585, 12.04381162,  7.9691873 , 10.12215626,  7.30915669,
        9.52652098,  7.45197362, 11.42555585,  9.91346315,  9.23867669,
        8.63175171,  4.68316208,  5.84933891, 11.32560779, 11.65

In [39]:
pred_test

array([ 6.07615237,  5.36502357,  5.09722489,  8.77000846,  5.03361917,
        6.20326216,  9.84302679, 10.2560556 ,  4.59361246,  6.30067642,
       11.03172247,  7.55873337, 10.8334278 ,  6.38572589,  3.45362391,
        4.36769027,  9.43950516,  9.29084997,  8.63610912,  8.02482672,
        7.48740575,  6.25995453,  6.6865435 , 11.86917144,  5.94918533,
        6.29360139, 10.35026705,  9.46652415,  5.86504607, 11.69775302,
       10.33883461,  7.18762214,  9.30065883, 11.00123733, 11.30991959,
        4.90318598, 11.16908796,  9.01518664,  4.00247733,  7.138915  ,
        6.91532331,  8.17348191,  9.65028521,  8.09972214,  5.38314392,
        8.25520797, 12.52133741,  6.32236456, 10.33788331,  5.80053014,
        9.28045153,  9.77169917,  8.48998772,  8.15086142,  8.53176256,
        8.95954722,  8.63521785,  2.26932673,  4.48926591,  6.59121619,
        5.23459038, 11.70904273, 11.56731983, 11.03865476, 13.1359843 ,
        8.82564788,  3.15884733,  8.83351252,  6.89616896,  8.97

In [40]:
err_train = lcn_train_y - pred_train
err_test = lcn_test_y - pred_test

In [41]:
err_train

242    0.770112
339   -0.467750
579    0.657511
2      0.161634
246   -0.070068
         ...   
87     0.499949
658   -0.158044
52    -0.703087
238    1.528313
707   -0.551718
Name: LungCap, Length: 580, dtype: float64

In [42]:
err_test

446    0.223848
451   -0.940024
254    0.202775
405    0.004992
171   -0.708619
         ...   
315   -1.536979
292    1.886544
636    0.585956
5      0.227108
653   -0.265669
Name: LungCap, Length: 145, dtype: float64

In [43]:
mse = np.mean(np.square(err_test))
mse

1.017135307077359

In [44]:
rmse = np.sqrt(mse)
rmse

1.0085312623202907

In [45]:
mape = np.mean(np.abs(err_test * 100/lcn_test_y))
mape

13.051464784473513